# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:38
from __future__ import unicode_literals

import VoteCumBlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=VoteCumBlog.models.upload_location)),
                ('content', models.TextField()),
                ('slug', models.SlugField(default=None, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
